
--ENLACE DE GITHUB https://github.com/Felipe9820/KDN_Project_Management_Tool_Final




--Crear la tabla CLIENTS
CREATE TABLE CLIENTS (
    ID_CLIENT INT PRIMARY KEY,
    CLIENT_NAME VARCHAR(255) NOT NULL,
    STATUS_CLIENT VARCHAR(50),
    SERVICES VARCHAR(255)
);

--Crear la tabla CLUSTERS
CREATE TABLE CLUSTERS_GROUPS (
    ID_CLUSTER INT PRIMARY KEY,
    CLUSTER_NAME VARCHAR(100) NOT NULL
);

--Crear la tabla COUNTRIES
CREATE TABLE COUNTRIES (
    ID_COUNTRY INT PRIMARY KEY,
    COUNTRY_NAME VARCHAR(100) NOT NULL
);

--Crear Tabla Custers Countries Relation
CREATE TABLE CLUSTERS_COUNTRIES_RELATION (
    ID_CLUSTER INT,
    ID_COUNTRY INT,
    CONSTRAINT PK_CLUSTER_COUNTRY_RELATION PRIMARY KEY (ID_CLUSTER, ID_COUNTRY),
    FOREIGN KEY (ID_COUNTRY) REFERENCES COUNTRIES(ID_COUNTRY)
);

--Crear la tabla BUSINESS_TYPES
CREATE TABLE BUSINESS_TYPES (
    BUSINESS_TYPE_ID INT PRIMARY KEY,
    BUSINESS_TYPE_NAME VARCHAR(100) NOT NULL
);

--Crear la tabla ENTITIES_PER_CLIENT
CREATE TABLE ENTITIES_PER_CLIENT (
    ID_ENTITY INT PRIMARY KEY,
    ID_CLIENT INT,
    COMPANY_INTERNAL_ID INT,
    COMPANY_NAME VARCHAR(255),
    LEGAL_ID VARCHAR(50),
    ID_CLUSTER INT,
    ID_COUNTRY INT,
    BUSINESS_TYPE_ID INT,
    FOREIGN KEY (ID_CLIENT) REFERENCES CLIENTS(ID_CLIENT),
    FOREIGN KEY (ID_CLUSTER, ID_COUNTRY) REFERENCES CLUSTERS_COUNTRIES_RELATION(ID_CLUSTER, ID_COUNTRY),
    FOREIGN KEY (BUSINESS_TYPE_ID) REFERENCES BUSINESS_TYPES(BUSINESS_TYPE_ID)
);

--Crear tabla Status
CREATE TABLE Status (
    Status_ID NUMBER PRIMARY KEY,
    Status_Name VARCHAR2(50) NOT NULL
);

--Crear tabla Final Status
CREATE TABLE Final_Status (
    ID_Final_Status NUMBER PRIMARY KEY,
    Status_Name VARCHAR2(50) NOT NULL
);

--Crear tabla Periodicity
CREATE TABLE Periodicity (
    ID_Periodicity NUMBER PRIMARY KEY,
    Periodicity_Name VARCHAR2(50) NOT NULL
);

--Crear tabla Category
CREATE TABLE Category (
    ID_Category NUMBER PRIMARY KEY,
    Category_Name VARCHAR2(50) NOT NULL
);

--Crear tabla Area
CREATE TABLE Area (
    ID_Area NUMBER PRIMARY KEY,
    Area_Name VARCHAR2(50) NOT NULL
);

--Crear tabla Processes
CREATE TABLE Processes (
    ID_Process NUMBER PRIMARY KEY,
    ID_User_Approver NUMBER,
    ID_User_Analyst NUMBER,
    Process VARCHAR2(100) NOT NULL,
    ID_Cluster INT,
    ID_Country INT,
    ID_Entity INT,
    ID_Area INT,
    ID_Category INT,
    Period VARCHAR2(20),
    Year INT,
    ID_Periodicity INT,
    Due_Date DATE,
    ID_Final_Status INT,
    CONSTRAINT fk_user_approver FOREIGN KEY (ID_User_Approver) REFERENCES Team_Structure(ID_User),
    CONSTRAINT fk_user_analyst FOREIGN KEY (ID_User_Analyst) REFERENCES Team_Structure(ID_User),
    CONSTRAINT fk_cluster_country_relation FOREIGN KEY (ID_Cluster, ID_Country) REFERENCES CLUSTERS_COUNTRIES_RELATION(ID_Cluster, ID_Country),
    CONSTRAINT fk_entity FOREIGN KEY (ID_Entity) REFERENCES Entities_Per_Client(ID_Entity),
    CONSTRAINT fk_area FOREIGN KEY (ID_Area) REFERENCES Area(ID_Area), 
    CONSTRAINT fk_category FOREIGN KEY (ID_Category) REFERENCES Category(ID_Category), 
    CONSTRAINT fk_periodicity FOREIGN KEY (ID_Periodicity) REFERENCES Periodicity(ID_Periodicity),
    CONSTRAINT fk_final_status FOREIGN KEY (ID_Final_Status) REFERENCES Final_Status(ID_Final_Status)
);

CREATE TABLE SERVICES (
    Service_ID INT PRIMARY KEY,
    Service_Name VARCHAR(255) NOT NULL
);

CREATE TABLE Roles (
    Role_ID NUMBER PRIMARY KEY,
    Role_Name VARCHAR2(50) NOT NULL
);

-- Insertar datos de roles
INSERT INTO Roles (Role_ID, Role_Name) VALUES (1, 'Manager');
INSERT INTO Roles (Role_ID, Role_Name) VALUES (2, 'Developer');
INSERT INTO Roles (Role_ID, Role_Name) VALUES (3, 'Designer');

-- Crear tabla para Team Structure
CREATE TABLE Team_Structure (
    ID_User NUMBER PRIMARY KEY,
    First_Name VARCHAR2(50) NOT NULL,
    Last_Name VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Role_ID NUMBER,
    Status_ID NUMBER,
    CONSTRAINT fk_role FOREIGN KEY (Role_ID) REFERENCES Roles(Role_ID),
    CONSTRAINT fk_status FOREIGN KEY (Status_ID) REFERENCES Status(Status_ID)
);

-- Agregar columna STATUS_ID a CLIENTS
ALTER TABLE CLIENTS
ADD STATUS_ID INT;

-- Agregar columna SERVICE_ID a CLIENTS
ALTER TABLE CLIENTS
ADD SERVICE_ID INT;

-- Agregar restricciones de clave externa a STATUS_ID y SERVICE_ID
ALTER TABLE CLIENTS
ADD CONSTRAINT fk_client_status FOREIGN KEY (STATUS_ID) REFERENCES Status(Status_ID);

ALTER TABLE CLIENTS
ADD CONSTRAINT fk_servicio FOREIGN KEY (SERVICE_ID) REFERENCES SERVICES(Service_ID);

-- Crear tabla Year
CREATE TABLE Year (
    Year_ID INT PRIMARY KEY
);

-- Crear tabla Period
CREATE TABLE Period (
    Period_ID INT PRIMARY KEY,
    Month VARCHAR(20)
);

--Creacion de Vistas
--Vista 1
CREATE VIEW Client_Entities AS
SELECT c.ID_CLIENT, c.CLIENT_NAME, e.COMPANY_NAME
FROM CLIENTS c
INNER JOIN ENTITIES_PER_CLIENT e ON c.ID_CLIENT = e.ID_CLIENT;
--Vista 2
CREATE VIEW Cluster_Country AS
SELECT cr.ID_CLUSTER, cg.CLUSTER_NAME, cn.COUNTRY_NAME
FROM CLUSTERS_COUNTRIES_RELATION cr
INNER JOIN CLUSTERS_GROUPS cg ON cr.ID_CLUSTER = cg.ID_CLUSTER
INNER JOIN COUNTRIES cn ON cr.ID_COUNTRY = cn.ID_COUNTRY;
--Vista 3
CREATE VIEW BusinessType_Entities AS
SELECT bt.BUSINESS_TYPE_NAME, e.COMPANY_NAME
FROM BUSINESS_TYPES bt
INNER JOIN ENTITIES_PER_CLIENT e ON bt.BUSINESS_TYPE_ID = e.BUSINESS_TYPE_ID;
--Vista 4
CREATE VIEW Process_Details AS
SELECT p.ID_Process, p.Process, p.Period, p.Year, per.Periodicity_Name, p.Due_Date
FROM Processes p
INNER JOIN Periodicity per ON p.ID_Periodicity = per.ID_Periodicity;
--Vista 5
CREATE VIEW Client_Services AS
SELECT ID_CLIENT, CLIENT_NAME, SERVICES
FROM CLIENTS;
--Vista 6
CREATE VIEW Process_FinalStatus AS
SELECT p.ID_Process, fs.Status_Name
FROM Processes p
INNER JOIN Final_Status fs ON p.ID_Final_Status = fs.ID_Final_Status;
--Vista 7
CREATE VIEW Client_Entity_Count AS
SELECT c.CLIENT_NAME, COUNT(e.ID_ENTITY) AS Entity_Count
FROM CLIENTS c
LEFT JOIN ENTITIES_PER_CLIENT e ON c.ID_CLIENT = e.ID_CLIENT
GROUP BY c.ID_CLIENT, c.CLIENT_NAME;
--Vista 8
CREATE VIEW Process_Analysts AS
SELECT p.ID_Process, u.FIRST_NAME || u.LAST_NAME AS Analyst_Name
FROM Processes p
INNER JOIN Team_Structure u ON p.ID_User_Analyst = u.ID_User;
--Vista 9
CREATE VIEW Process_Approvers AS
SELECT p.ID_Process, u.FIRST_NAME || u.LAST_NAME AS Approver_Name
FROM Processes p
INNER JOIN Team_Structure u ON p.ID_User_Approver = u.ID_User;
--Vista 10
CREATE VIEW Entity_Country AS
SELECT e.COMPANY_NAME, cn.COUNTRY_NAME
FROM ENTITIES_PER_CLIENT e
INNER JOIN CLUSTERS_COUNTRIES_RELATION cr ON e.ID_CLUSTER = cr.ID_CLUSTER AND e.ID_COUNTRY = cr.ID_COUNTRY
INNER JOIN COUNTRIES cn ON cr.ID_COUNTRY = cn.ID_COUNTRY;

-- Insertar datos en la tabla Year (por ejemplo, para a√±os del 2020 al 2025)
INSERT INTO Year (Year_ID) VALUES (2020);
INSERT INTO Year (Year_ID) VALUES (2021);
INSERT INTO Year (Year_ID) VALUES (2022);
INSERT INTO Year (Year_ID) VALUES (2023);
INSERT INTO Year (Year_ID) VALUES (2024);
INSERT INTO Year (Year_ID) VALUES (2025);

-- Insertar datos en la tabla Period (todos los meses)
INSERT INTO Period (Period_ID, Month) VALUES (1, 'January');
INSERT INTO Period (Period_ID, Month) VALUES (2, 'February');
INSERT INTO Period (Period_ID, Month) VALUES (3, 'March');
INSERT INTO Period (Period_ID, Month) VALUES (4, 'April');
INSERT INTO Period (Period_ID, Month) VALUES (5, 'May');
INSERT INTO Period (Period_ID, Month) VALUES (6, 'June');
INSERT INTO Period (Period_ID, Month) VALUES (7, 'July');
INSERT INTO Period (Period_ID, Month) VALUES (8, 'August');
INSERT INTO Period (Period_ID, Month) VALUES (9, 'September');
INSERT INTO Period (Period_ID, Month) VALUES (10, 'October');
INSERT INTO Period (Period_ID, Month) VALUES (11, 'November');
INSERT INTO Period (Period_ID, Month) VALUES (12, 'December');

--Insert en SERVICES
INSERT ALL
INTO SERVICES (Service_ID, Service_Name) VALUES (1, 'Full Management Services')
INTO SERVICES (Service_ID, Service_Name) VALUES (2, 'CIT')
INTO SERVICES (Service_ID, Service_Name) VALUES (3, 'Full Bookkeeping')
INTO SERVICES (Service_ID, Service_Name) VALUES (4, 'Direct/Indirect Tax')
INTO SERVICES (Service_ID, Service_Name) VALUES (5, 'Accounts Payable')
INTO SERVICES (Service_ID, Service_Name) VALUES (6, 'Accounts Receivable')
SELECT 1 FROM DUAL;

--Insert en Clusters Countries Relation
INSERT ALL
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (7, 1)  -- Argentina
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (7, 2)  -- Brazil
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (2, 3)  -- Canada
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (4, 4)  -- China
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (5, 5)  -- Egypt
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (3, 6)  -- France
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (3, 7)  -- Germany
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (4, 8)  -- India
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (3, 9)  -- Italy
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (4, 10) -- Japan
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (7, 11) -- Mexico
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (3, 12) -- Netherlands
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (6, 13) -- New Zealand
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (5, 14) -- Nigeria
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (7, 15) -- Peru
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (4, 16) -- Russia
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (5, 17) -- South Africa
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (3, 18) -- Spain
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (3, 19) -- Sweden
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (3, 20) -- Switzerland
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (3, 21) -- United Kingdom
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (2, 22) -- United States
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (6, 23) -- Australia
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (7, 24) -- Chile
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (7, 25) -- Colombia
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (26, 26) -- Denmark
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (30, 27) -- Finland
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (4, 28) -- Greece
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (29, 29) -- Hong Kong
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (4, 30) -- Indonesia
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (30, 31) -- Ireland
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (4, 32) -- Israel
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (4, 33) -- Jamaica
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (5, 34) -- Kenya
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (3, 35) -- Luxembourg
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (4, 36) -- Malaysia
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (30, 37) -- Norway
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (4, 38) -- Pakistan
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (3, 39) -- Portugal
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (4, 40) -- Saudi Arabia
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (29, 41) -- Singapore
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (42, 42) -- South Korea
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (42, 43) -- Taiwan
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (4, 44) -- Thailand
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (45, 45) -- Turkey
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (46, 46) -- UAE
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (7, 47) -- Uruguay
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (7, 48) -- Venezuela
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (4, 49) -- Vietnam
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (5, 50) -- Zimbabwe
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (1, 51) -- Guatemala
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (1, 52) -- Honduras
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (1, 53) -- Nicaragua
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (1, 54) -- Costa Rica
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (1, 55) -- El Salvador
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (1, 56) -- Panama
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (1, 57) -- Belize
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (1, 58) -- Haiti
INTO CLUSTERS_COUNTRIES_RELATION (ID_CLUSTER, ID_COUNTRY) VALUES (1, 59) -- Dominican Republic
SELECT * FROM dual;


--Insert en la tabla Business Types
INSERT ALL
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (1, 'Technology')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (2, 'Finance')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (3, 'Healthcare')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (4, 'Manufacturing')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (5, 'Retail')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (6, 'Hospitality')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (7, 'Education')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (8, 'Energy')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (9, 'Telecommunications')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (10, 'Transportation')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (11, 'Agriculture')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (12, 'Media and Entertainment')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (13, 'Automotive')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (14, 'Real Estate')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (15, 'Consulting')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (16, 'Biotechnology')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (17, 'Pharmaceuticals')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (18, 'Food and Beverage')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (19, 'Legal Services')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (20, 'Environmental Services')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (21, 'Government')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (22, 'Non-Profit')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (23, 'Fashion')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (24, 'Sports and Recreation')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (25, 'Travel and Tourism')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (26, 'Utilities')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (27, 'Insurance')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (28, 'Logistics')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (29, 'Marketing')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (30, 'Software')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (31, 'Hardware')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (32, 'E-commerce')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (33, 'Advertising')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (34, 'Construction')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (35, 'Fitness')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (36, 'Art and Design')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (37, 'Security')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (38, 'Gaming')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (39, 'Social Services')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (40, 'Renewable Energy')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (41, 'Fitness')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (42, 'Research')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (43, 'Architecture')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (44, 'Event Management')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (45, 'Interior Design')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (46, 'Human Resources')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (47, 'Pharmaceuticals')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (48, 'Forestry')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (49, 'Waste Management')
INTO BUSINESS_TYPES (BUSINESS_TYPE_ID, BUSINESS_TYPE_NAME) VALUES (50, 'Renovation')
SELECT * FROM dual;

-- INSERT con 25 clientes
INSERT ALL
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (1, 'ABC Solutions', 'Activo', 'Servicio A')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (2, 'XYZ Innovations', 'Activo', 'Servicio B')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (3, 'Pinnacle Technologies', 'Activo', 'Servicio C')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (4, 'Infinite Dynamics', 'Activo', 'Servicio D')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (5, 'Nebula Enterprises', 'Activo', 'Servicio E')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (6, 'Galactic Innovators', 'Activo', 'Servicio F')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (7, 'Quantum Systems', 'Activo', 'Servicio G')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (8, 'Vertex Dynamics', 'Activo', 'Servicio H')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (9, 'Astral Technologies', 'Activo', 'Servicio I')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (10, 'Global Innovations', 'Activo', 'Servicio J')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (11, 'Tech Galaxy Solutions', 'Activo', 'Servicio K')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (12, 'Epic Systems', 'Activo', 'Servicio L')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (13, 'Quantum Innovations', 'Activo', 'Servicio M')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (14, 'Unified Dynamics', 'Activo', 'Servicio N')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (15, 'Intelligent Enterprises', 'Activo', 'Servicio O')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (16, 'Alpha Innovators', 'Activo', 'Servicio P')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (17, 'Beta Dynamics', 'Activo', 'Servicio Q')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (18, 'Omega Technologies', 'Activo', 'Servicio R')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (19, 'Zeta Solutions', 'Activo', 'Servicio S')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (20, 'Infinity Innovations', 'Activo', 'Servicio T')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (21, 'Eclipse Enterprises', 'Activo', 'Servicio U')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (22, 'Solar Systems', 'Activo', 'Servicio V')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (23, 'Stellar Innovations', 'Activo', 'Servicio W')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (24, 'Nebula Dynamics', 'Activo', 'Servicio X')
INTO CLIENTS (ID_CLIENT, CLIENT_NAME, STATUS_CLIENT, SERVICES) VALUES (25, 'Quantum Enterprises', 'Activo', 'Servicio Y')
SELECT * FROM dual;

--Inserts Entities
INSERT ALL
-- Cliente 1
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (1, 1, 101, 'ABC Solutions Internal', 'ABC123', 1, 51, 1)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (2, 1, 102, 'ABC Subsidiary', 'ABC456', 1, 52, 2)
-- Cliente 2
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (3, 2, 201, 'XYZ Innovations Internal', 'XYZ123', 7, 1, 3)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (4, 2, 202, 'XYZ Subsidiary', 'XYZ456', 7, 2, 4)
-- Cliente 3
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (5, 3, 301, 'Pinnacle Tech Solutions', 'PTS123', 3, 6, 5)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (6, 3, 302, 'Pinnacle Subsidiary', 'PTS456', 3, 7, 6)
-- Cliente 4
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (7, 4, 401, 'Infinite Dynamics Internal', 'ID123', 4, 8, 7)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (8, 4, 402, 'Infinite Subsidiary', 'ID456', 4, 9, 8)
-- Cliente 5
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (9, 5, 501, 'Nebula Enterprises Internal', 'NE123', 5, 10, 9)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (10, 5, 502, 'Nebula Subsidiary', 'NE456', 5, 11, 10)
-- Cliente 6
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (11, 6, 601, 'Galactic Innovators Internal', 'GI123', 6, 12, 11)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (12, 6, 602, 'Galactic Subsidiary', 'GI456', 6, 13, 12)
-- Cliente 7
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (13, 7, 701, 'Quantum Systems Internal', 'QS123', 7, 14, 13)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (14, 7, 702, 'Quantum Subsidiary', 'QS456', 7, 15, 14)
-- Cliente 8
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (15, 8, 801, 'Vertex Dynamics Internal', 'VD123', 3, 16, 15)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (16, 8, 802, 'Vertex Subsidiary', 'VD456', 3, 17, 16)
-- Cliente 9
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (17, 9, 901, 'Astral Tech Solutions', 'ATS123', 4, 18, 17)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (18, 9, 902, 'Astral Subsidiary', 'ATS456', 4, 19, 18)
-- Cliente 10
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (19, 10, 1001, 'Global Innovations Internal', 'GI123', 5, 20, 19)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (20, 10, 1002, 'Global Subsidiary', 'GI456', 5, 21, 20)
-- Cliente 11
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (21, 11, 1101, 'Tech Galaxy Solutions Internal', 'TGS123', 6, 22, 21)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (22, 11, 1102, 'Tech Subsidiary', 'TGS456', 6, 23, 22)
-- Cliente 12
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (23, 12, 1201, 'Epic Systems Internal', 'ES123', 7, 24, 23)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (24, 12, 1202, 'Epic Subsidiary', 'ES456', 7, 25, 24)
-- Cliente 13
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (25, 13, 1301, 'Quantum Innovations Internal', 'QI123', 8, 26, 25)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (26, 13, 1302, 'Quantum Subsidiary', 'QI456', 8, 27, 26)
-- Cliente 14
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (27, 14, 1401, 'Unified Dynamics Internal', 'UD123', 9, 28, 27)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (28, 14, 1402, 'Unified Subsidiary', 'UD456', 9, 29, 28)
-- Cliente 15
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (29, 15, 1501, 'Intelligent Enterprises Internal', 'IE123', 10, 30, 29)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (30, 15, 1502, 'Intelligent Subsidiary', 'IE456', 10, 31, 30)
-- Cliente 16
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (31, 16, 1601, 'Alpha Innovators Internal', 'AI123', 11, 32, 31)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (32, 16, 1602, 'Alpha Subsidiary', 'AI456', 11, 33, 32)
-- Cliente 17
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (33, 17, 1701, 'Beta Dynamics Internal', 'BD123', 12, 34, 33)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (34, 17, 1702, 'Beta Subsidiary', 'BD456', 12, 35, 34)
-- Cliente 18
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (35, 18, 1801, 'Omega Technologies Internal', 'OT123', 13, 36, 35)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (36, 18, 1802, 'Omega Subsidiary', 'OT456', 13, 37, 36)
-- Cliente 19
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (37, 19, 1901, 'Zeta Solutions Internal', 'ZS123', 14, 38, 37)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (38, 19, 1902, 'Zeta Subsidiary', 'ZS456', 14, 39, 38)
-- Cliente 20
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (39, 20, 2001, 'Infinity Innovations Internal', 'II123', 15, 40, 39)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (40, 20, 2002, 'Infinity Subsidiary', 'II456', 15, 41, 40)
-- Cliente 21
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (41, 21, 2101, 'Eclipse Enterprises Internal', 'EE123', 16, 42, 41)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (42, 21, 2102, 'Eclipse Subsidiary', 'EE456', 16, 43, 42)
-- Cliente 22
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (43, 22, 2201, 'Solar Systems Internal', 'SSI123', 17, 44, 43)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (44, 22, 2202, 'Solar Subsidiary', 'SSI456', 17, 45, 44)
-- Cliente 23
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (45, 23, 2301, 'Stellar Innovations Internal', 'SII123', 18, 46, 45)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (46, 23, 2302, 'Stellar Subsidiary', 'SII456', 18, 47, 46)
-- Cliente 24
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (47, 24, 2401, 'Nebula Dynamics Internal', 'NDI123', 19, 48, 47)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (48, 24, 2402, 'Nebula Subsidiary', 'NDI456', 19, 49, 48)
-- Cliente 25
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (49, 25, 2501, 'Quantum Enterprises Internal', 'QEI123', 20, 50, 49)
INTO ENTITIES_PER_CLIENT (ID_ENTITY, ID_CLIENT, COMPANY_INTERNAL_ID, COMPANY_NAME, LEGAL_ID, ID_CLUSTER, ID_COUNTRY, BUSINESS_TYPE_ID) 
VALUES (50, 25, 2502, 'Quantum Subsidiary', 'QEI456', 20, 51, 50)
SELECT * FROM dual;

-- Insertar datos en la tabla Processes
INSERT ALL
INTO Processes (ID_Process, ID_User_Approver, ID_User_Analyst, Process, ID_Cluster, ID_Country, ID_Entity, ID_Area, ID_Category, Period, Year, ID_Periodicity, Due_Date, ID_Final_Status) VALUES (1, 1, 1, 'Process 1', 1, 54, 1, 1, 1, 'January', 2024, 1, TO_DATE('2024-03-31', 'YYYY-MM-DD'), 3)
INTO Processes (ID_Process, ID_User_Approver, ID_User_Analyst, Process, ID_Cluster, ID_Country, ID_Entity, ID_Area, ID_Category, Period, Year, ID_Periodicity, Due_Date, ID_Final_Status) VALUES (2, 2, 2, 'Process 2', 7, 1, 2, 2, 2, 'February', 2024, 2, TO_DATE('2024-06-30', 'YYYY-MM-DD'), 3)
INTO Processes (ID_Process, ID_User_Approver, ID_User_Analyst, Process, ID_Cluster, ID_Country, ID_Entity, ID_Area, ID_Category, Period, Year, ID_Periodicity, Due_Date, ID_Final_Status) VALUES (3, 3, 3, 'Process 3', 2, 3, 3, 3, 1, 'March', 2024, 2, TO_DATE('2024-09-30', 'YYYY-MM-DD'), 3)
INTO Processes (ID_Process, ID_User_Approver, ID_User_Analyst, Process, ID_Cluster, ID_Country, ID_Entity, ID_Area, ID_Category, Period, Year, ID_Periodicity, Due_Date, ID_Final_Status) VALUES (4, 1, 1, 'Process 4', 4, 4, 4, 4, 2, 'April', 2024, 2, TO_DATE('2024-12-31', 'YYYY-MM-DD'), 3)
INTO Processes (ID_Process, ID_User_Approver, ID_User_Analyst, Process, ID_Cluster, ID_Country, ID_Entity, ID_Area, ID_Category, Period, Year, ID_Periodicity, Due_Date, ID_Final_Status) VALUES (5, 2, 2, 'Process 5', 5, 5, 5, 5, 3, 'May', 2025, 2, TO_DATE('2025-03-31', 'YYYY-MM-DD'), 3)
SELECT * FROM dual;

-- Insertar datos en la tabla CLUSTERS_GROUPS
INSERT ALL
INTO CLUSTERS_GROUPS (ID_CLUSTER, CLUSTER_NAME) VALUES (1, 'Latinoam√©rica')
INTO CLUSTERS_GROUPS (ID_CLUSTER, CLUSTER_NAME) VALUES (2, 'Norteam√©rica')
INTO CLUSTERS_GROUPS (ID_CLUSTER, CLUSTER_NAME) VALUES (3, 'Europa')
INTO CLUSTERS_GROUPS (ID_CLUSTER, CLUSTER_NAME) VALUES (4, 'Asia')
INTO CLUSTERS_GROUPS (ID_CLUSTER, CLUSTER_NAME) VALUES (5, '√?frica')
INTO CLUSTERS_GROUPS (ID_CLUSTER, CLUSTER_NAME) VALUES (6, 'Ocean√≠a')
INTO CLUSTERS_GROUPS (ID_CLUSTER, CLUSTER_NAME) VALUES (7, 'Suram√©rica')
SELECT * FROM dual;

-- Insertar datos en la tabla Final Status
INSERT INTO Final_Status (ID_Final_Status, Status_Name) VALUES (1, 'Approved');
INSERT INTO Final_Status (ID_Final_Status, Status_Name) VALUES (2, 'Rejected');
INSERT INTO Final_Status (ID_Final_Status, Status_Name) VALUES (3, 'Pending');

-- Insertar datos en la tabla Periodicity
INSERT INTO Periodicity (ID_Periodicity, Periodicity_Name) VALUES (1, 'Monthly');
INSERT INTO Periodicity (ID_Periodicity, Periodicity_Name) VALUES (2, 'Quarterly');
INSERT INTO Periodicity (ID_Periodicity, Periodicity_Name) VALUES (3, 'Annual');

-- Insertar datos en la tabla Category
INSERT INTO Category (ID_Category, Category_Name) VALUES (1, 'Self-Liquidative');
INSERT INTO Category (ID_Category, Category_Name) VALUES (2, 'Informative');
INSERT INTO Category (ID_Category, Category_Name) VALUES (3, 'Survey');
INSERT INTO Category (ID_Category, Category_Name) VALUES (4, 'Only Pay');

-- Insertar datos en la tabla Area
INSERT INTO Area (ID_Area, Area_Name) VALUES (1, 'Indirect Tax');
INSERT INTO Area (ID_Area, Area_Name) VALUES (2, 'Direct Tax');
INSERT INTO Area (ID_Area, Area_Name) VALUES (3, 'Transfer Pricing');
INSERT INTO Area (ID_Area, Area_Name) VALUES (4, 'Stats');
INSERT INTO Area (ID_Area, Area_Name) VALUES (5, 'Projects');

--Selects para ciertas tablas
SELECT * FROM Final_Status;
SELECT * FROM Category;
SELECT * FROM Area;
SELECT * FROM CLUSTERS_GROUPS;
SELECT * FROM CLIENTS;
SELECT * FROM Periodicity;

--Eliminar datos para manejo de errores
DELETE FROM CLIENTS;
DElETE FROM Processes;


-------------------------------------
---------------Stored Proceduces----
------------------insertar cliente------------------
CREATE OR REPLACE PROCEDURE P_insertar_cliente (
    V_NOMBRE IN VARCHAR2,
    p_STATUS IN VARCHAR2,
    p_SERVICIO IN VARCHAR2
)
as
    v_id_cliente NUMBER;
BEGIN
    -- Se le agrega un id segun la insercion
    SELECT NVL(MAX(id_client), 0) + 1 INTO v_id_cliente FROM clients;

    -- Insertar el nuevo cliente en la tabla
    INSERT INTO clients (id_client, CLIENT_NAME, STATUS_CLIENT, SERVICES)
    VALUES (v_id_cliente, V_NOMBRE, p_STATUS, p_SERVICIO);

    DBMS_OUTPUT.PUT_LINE('Cliente registrado correctamente con ID: ' || v_id_cliente);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al registrar el cliente: ' || SQLERRM);
END P_insertar_cliente;

BEGIN
P_insertar_cliente('Felipe','Activo','Servicio A');
END;
/

---------------------eliminar clientes-----------------
CREATE OR REPLACE PROCEDURE P_eliminar_cliente(
    p_id_cliente IN NUMBER
)
as
BEGIN
    -- Borrar el cliente de la tabla
    DELETE FROM clients WHERE id_client = p_id_cliente;

    DBMS_OUTPUT.PUT_LINE('Cliente con ID ' || p_id_cliente || ' eliminado correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al borrar el cliente: ' || SQLERRM);
END P_eliminar_cliente;

begin 
p_eliminar_cliente(2);
end;
/
-----------------Actualizar clientes-------------------
CREATE OR REPLACE PROCEDURE P_Actualizar_Cliente (
    p_id_cliente IN NUMBER,
    p_nombre_cliente IN VARCHAR2,
    p_status IN VARCHAR2,
    p_servicio IN VARCHAR2
)
as
BEGIN
    -------- Se actualiza la informaciÛn del cliente -------
    UPDATE clients
    SET   client_name = p_nombre_cliente,
        status_client = p_status,
        services = p_servicio
    WHERE id_client = p_id_cliente;

    DBMS_OUTPUT.PUT_LINE('Cliente con ID ' || p_id_cliente || ' actualizado correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al actualizar el cliente: ' || SQLERRM);
END P_Actualizar_Cliente;
execute P_Actualizar_Cliente(1, 'Alfredo', 'Activo', 'null');





/



---------------Actualizar status cliente------------
CREATE OR REPLACE PROCEDURE P_Actualizar_Status_Clientes(
    v_id_cliente IN NUMBER,
    v_nuevo_status IN VARCHAR2
) as

BEGIN
    UPDATE clients
    SET status_client = v_nuevo_status
    WHERE v_id_cliente = id_client;
    
    COMMIT;
    
    DBMS_OUTPUT.PUT_LINE('El status del empleado con ID ' || v_id_cliente || ' ha sido actualizado a ' || v_nuevo_status);
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('No se encontrÛ un empleado con el ID proporcionado');
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('OcurriÛ un error al actualizar el status del empleado');
END P_Actualizar_Status_Clientes;


  execute  P_Actualizar_Status_Clientes(1, 'Inactivo');


---------------------Actualizar final status--------------------
CREATE OR REPLACE PROCEDURE P_Actualizar_Status_Final (
    p_id_final_status IN NUMBER,
    p_nuevo_status IN VARCHAR2
)
as
BEGIN
    -- Actualizar el estado final 
    UPDATE FINAL_STATUS
    SET STATUS_NAME = p_nuevo_status
    WHERE ID_FINAL_STATUS = p_id_final_status;


    DBMS_OUTPUT.PUT_LINE('Estado final actualizado correctamente para el registro con ID ' || p_id_final_status);
EXCEPTION
    WHEN OTHERS THEN
        
        DBMS_OUTPUT.PUT_LINE('Error al actualizar el estado final: ' || SQLERRM);
END P_Actualizar_Status_Final;


   execute P_Actualizar_Status_Final(1, 'REJECT');


/

-----------------------Insertar un pais
CREATE OR REPLACE PROCEDURE P_Insertar_Country (
    V_Nombre_pais IN VARCHAR2
)
as
    v_id_pais NUMBER;
BEGIN
    -- Se le agrega un id segun la insercion
    SELECT NVL(MAX(id_country), 0) + 1 INTO v_id_pais FROM Countries;

    -- Inserta el nuevo pais 
    INSERT INTO Countries (id_country, country_name)
    VALUES (v_id_pais, V_Nombre_pais);

    DBMS_OUTPUT.PUT_LINE('Cliente registrado correctamente con ID: ' || v_id_pais);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al registrar el cliente: ' || SQLERRM);
END P_Insertar_Country;


execute P_Insertar_Country ('Guyana');

/


---------------Eliminar pais----------------\
CREATE OR REPLACE PROCEDURE P_Eliminar_Pais(
    p_id_pais IN NUMBER
)
as
BEGIN
    -- Borrar el pais 
    DELETE FROM Countries WHERE id_country = p_id_pais;

   
    DBMS_OUTPUT.PUT_LINE('Cliente con ID ' || p_id_pais || ' eliminado correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        
        DBMS_OUTPUT.PUT_LINE('Error al borrar el cliente: ' || SQLERRM);
END P_Eliminar_Pais;

 
execute P_Eliminar_Pais(2);

/
/
/

-------------insertar areas-----------
CREATE OR REPLACE PROCEDURE P_Insertar_Area(
    V_Nombre_Area IN VARCHAR2
)
as
    v_id_Area NUMBER;
BEGIN
    -- Se le agrega un id segun la insercion
    SELECT NVL(MAX(id_area), 0) + 1 INTO v_id_Area FROM area;

    -- Inserta el nuevo area 
    INSERT INTO area (id_area, area_name)
    VALUES (v_id_Area, V_Nombre_Area);
--execpciones
    DBMS_OUTPUT.PUT_LINE('Area registrada correctamente con ID: ' || v_id_Area);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al registrar el area: ' || SQLERRM);
END P_Insertar_Area;


  execute  P_Insertar_Area ('Indirect Tax');

/
/
/

--------------eliminar area---------

CREATE OR REPLACE PROCEDURE P_Eliminar_Area(
    p_id_area IN NUMBER
)
as
BEGIN
    ----- Borrar el area -----
    DELETE FROM area WHERE id_area= p_id_area;

   
    DBMS_OUTPUT.PUT_LINE('Cliente con ID ' || p_id_area || ' eliminado correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        
        DBMS_OUTPUT.PUT_LINE('Error al borrar el cliente: ' || SQLERRM);
END P_Eliminar_Area;


execute P_Eliminar_Area(1);

/
/
/   
----------insertar roll--------
CREATE OR REPLACE PROCEDURE P_Insertar_Rol(
    v_Nombre_Rol IN VARCHAR2
)
as
    v_id_Rol NUMBER;
BEGIN
    -- Se le agrega un id segun la insercion
    SELECT NVL(MAX(ROLE_ID), 0) + 1 INTO v_id_Rol FROM ROLES;

    -- Inserta el nuevo role 
    INSERT INTO ROLES (ROLE_ID, Role_Name)
    VALUES (v_id_Rol, v_Nombre_Rol);
--execpciones
    DBMS_OUTPUT.PUT_LINE('Area registrada correctamente con ID: ' || v_id_Rol);
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Error al registrar el area: ' || SQLERRM);
END P_Insertar_Rol;


     execute P_Insertar_Rol ('Developer');

/
/
/
--------------eliminar rol---------

CREATE OR REPLACE PROCEDURE P_Eliminar_Rol(
    p_id_Rol IN NUMBER
)
as
BEGIN
    ----- Borrar el ROL -----
    DELETE FROM Roles WHERE ROLE_ID= p_id_Rol;

   
    DBMS_OUTPUT.PUT_LINE('Rol con ID ' || p_id_Rol || ' eliminado correctamente.');
EXCEPTION
    WHEN OTHERS THEN
        
        DBMS_OUTPUT.PUT_LINE('Error al borrar el cliente: ' || SQLERRM);
END P_Eliminar_Rol;


execute P_Eliminar_Rol(1);

/ 



-------------------------------------
-------------FUNCIONES---------------
CREATE OR REPLACE FUNCTION Cantidad_Paises
RETURN NUMBER
IS
  Cantidad NUMBER;
BEGIN
  SELECT COUNT(*) INTO Cantidad FROM countries;
  RETURN Cantidad;
END;
SELECT Cantidad_Paises as Cantidad_de_paises_Activos FROM Countries;

